spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true


  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true

  # Configuración de JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true

